from django.urls import path

from relay.api.views import (
    ApprovalLinkDecisionView,
    ApprovalLinkView,
    ApprovalRequestDetailView,
    ChannelConnectionCollectionView,
    MediaUploadConfirmView,
    MediaUploadIntentView,
    MetaOAuthCallbackView,
    MetaOAuthStartView,
    PostApprovalView,
    PostApprovalRequestView,
    PostCollectionView,
    PostDetailView,
    PublicationCollectionView,
    PublicationDetailView,
    PanelCsrfView,
    PanelLoginView,
    PanelLogoutView,
    PanelMeView,
    PanelSummaryView,
)

urlpatterns = [
    path("panel/csrf/", PanelCsrfView.as_view(), name="panel-csrf"),
    path("panel/login/", PanelLoginView.as_view(), name="panel-login"),
    path("panel/logout/", PanelLogoutView.as_view(), name="panel-logout"),
    path("panel/me/", PanelMeView.as_view(), name="panel-me"),
    path("panel/summary/", PanelSummaryView.as_view(), name="panel-summary"),
    path("connections/", ChannelConnectionCollectionView.as_view(), name="channel-connection-collection"),
    path("oauth/meta/start/", MetaOAuthStartView.as_view(), name="meta-oauth-start"),
    path("oauth/meta/callback/", MetaOAuthCallbackView.as_view(), name="meta-oauth-callback"),
    path("media/upload-intents/", MediaUploadIntentView.as_view(), name="media-upload-intent"),
    path("media/<uuid:media_asset_id>/confirm/", MediaUploadConfirmView.as_view(), name="media-upload-confirm"),
    path("posts/", PostCollectionView.as_view(), name="post-collection"),
    path("posts/<uuid:post_id>/", PostDetailView.as_view(), name="post-detail"),
    path("posts/<uuid:post_id>/approve/", PostApprovalView.as_view(), name="post-approval"),
    path(
        "posts/<uuid:post_id>/approval-requests/",
        PostApprovalRequestView.as_view(),
        name="post-approval-request",
    ),
    path("approval-links/<str:token>/", ApprovalLinkView.as_view(), name="approval-link"),
    path(
        "approval-links/<str:token>/decision/",
        ApprovalLinkDecisionView.as_view(),
        name="approval-link-decision",
    ),
    path(
        "approval-requests/<uuid:approval_request_id>/",
        ApprovalRequestDetailView.as_view(),
        name="approval-request-detail",
    ),
    path("publications/", PublicationCollectionView.as_view(), name="publication-collection"),
    path(
        "publications/<uuid:publication_id>/",
        PublicationDetailView.as_view(),
        name="publication-detail",
    ),
]
